### ISSUE TITLE
createMarketOrder => createOrder || createWorkOrder

### ISSUE THREAD

**Issue by sulliwane** [iExecBlockchainComputing/PoCo#23]
a "market order" has a very specific meaning in exchanges worlds, which is "an order to be executed immediately, at the market price".

In our case, I believe this variable name was supposed to refer to the borader meaning of "an order on the marketplace" and not to the specific "market order" meaning, so maybe we should consider renaming (or make a clear statement about it).

**Comment by Amxx** [comment]
Irrelevant with v3 changes to orders. Now WorkerpoolOrder and RequestOrder
