### ISSUE TITLE
`truffle migrate` fails since truffle v5.7.0

### ISSUE THREAD

**Issue by 0xalexbel** [iExecBlockchainComputing/PoCo#47]
Since version 5.7.0, running `truffle migrate` on a new test chain fails (with ganache chainId=1337). Calls to `artifacts.require(...)` and `<obj>.deploye()` are failing in various migration scripts . 

For example, In [4_deploy_core.js](https://github.com/iExecBlockchainComputing/PoCo/blob/5138f2d2275c5e983d89609035a236697fe891fb/migrations/4_deploy_core.js#L205) :
`TokenInstance = await RLC.deployed()` is failing. truffle is not able to retrieve the deployed address. 

The problem is mostly due to the fact that the ABI json file resolve algorithm has changed since between truffle v5.6.9 and v5.7.0

**Comment by jeremyjams** [comment]
Thanks, closing issue, see https://github.com/iExecBlockchainComputing/PoCo/pull/48#issuecomment-2551558750.
